
name: Deploy SPA (Angular) to Static Website + Purge AFD
on:
  push:
    branches: [ master ]
    paths:
      - 'spa/**'
      - '.github/workflows/deploy-spa.yml'

env:
  AZURE_RG: ${{ vars.AZURE_RG }}
  STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
  AFD_PROFILE: ${{ vars.AFD_PROFILE }}
  AFD_ENDPOINT: ${{ vars.AFD_ENDPOINT }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-spa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Angular
        working-directory: spa/minimalamp-spa
        run: |
          npm ci
          npm run build --if-present || npx ng build

      - name: Upload to Static Website ($web)
        run: |
          az storage blob upload-batch \
            -s "spa/minimalamp-spa/dist/minimalamp-spa" \
            -d '$web' \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --overwrite \
            --auth-mode login

      - name: Purge AFD endpoint cache
        if: ${{ env.AFD_PROFILE != '' && env.AFD_ENDPOINT != '' }}
        run: |
          az afd endpoint purge \
            --resource-group "$AZURE_RG" \
            --profile-name "$AFD_PROFILE" \
            --endpoint-name "$AFD_ENDPOINT" \
            --content-paths "/*"
